//= error nil
//= stderr "nil check failed\n2: f(Foo): 10\n1: main(): 6\n"

fun main() {
  f(Foo(1));
  f(nil);
}

fun f(x: Foo) {
  assert(id(x).y == 1);
}

fun id(x: Foo): Foo {
  return x;
}

class Foo(let y: Int32)
