//= error assert
//= output "assert failed\n0: foo(): 9\n1: call(String): 22\n2: main(): 5\n"

fun main() {
    call("foo");
}

fun foo() {
    assert(false);
}
